# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

for_platform :android do
    for_lane :deploy_to_alpha do
        json_key_file ENV("gcp_api_json_key_file_path_alpha")
        package_name("io.kort.inbooks.dev")
        signing_store_file_path ENV("signing_store_file_path_alpha")
        signing_store_password ENV("signing_store_password_alpha")
        signing_key_alias ENV("signing_store_password_alpha")
        signing_key_password ENV("signing_store_password_alpha")
    end
end

platform :android do
    lane  :deploy_to_alpha do |options|
       deploy(version_name: options[:version_name])
    end

    lane :deploy_to_production do |options|
        deploy(version_name: options[:version_name])
    end

    lane :deploy do |options|
        gradle(task: "clean", project_dir: "../../",)
        track = "internal"
        current_version_codes = google_play_track_version_codes(track: track)
        version_code = current_version_codes[0].to_i + 1
        gradle(
            task: "bundle",
            build_type: "Release",
            project_dir: "../../",
            properties: {
                "android.injected.signing.store.file" => CredentialsManager::AppfileConfig.try_fetch_value(:signing_store_file_path),
                "android.injected.signing.store.password" => CredentialsManager::AppfileConfig.try_fetch_value(:signing_store_password),
                "android.injected.signing.key.alias" => CredentialsManager::AppfileConfig.try_fetch_value(:signing_key_alias),
                "android.injected.signing.key.password" => CredentialsManager::AppfileConfig.try_fetch_value(:signing_key_password),
                "version.code" => version_code,
                "version.name" => options[:version_name] || "",
            }
        )
        upload_to_play_store(
            track: track,
            skip_upload_metadata: true,
            skip_upload_images: true,
            skip_upload_screenshots: true
        )
    end
end