default_platform(:android)

platform :android do
    lane :deploy_to_alpha do |options|
       deploy(version_name: options[:version_name])
    end

    lane :deploy_to_production do |options|
        deploy(version_name: options[:version_name])
    end

    lane :deploy do |options|
        gradle(task: "clean", project_dir: "../../",)
        track = "internal"
        current_version_codes = google_play_track_version_codes(track: track)
        version_code = current_version_codes[0].to_i + 1
        
        gradle(
            task: "bundle",
            build_type: "Release",
            project_dir: "../../",
            properties: {
                "android.injected.signing.store.file" => ENV["signing_store_file_path"],
                "android.injected.signing.store.password" => ENV["signing_store_password"],
                "android.injected.signing.key.alias" => ENV["signing_key_alias"],
                "android.injected.signing.key.password" => ENV["signing_key_password"],
                "version.code" => version_code,
                "version.name" => options[:version_name] || "",
            }
        )
        upload_to_play_store(
            track: track,
            skip_upload_metadata: true,
            skip_upload_images: true,
            skip_upload_screenshots: true
        )
    end
end