services:
  postgres_test:
    image: postgres
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: "inbooks"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    command: -p 5433