services:
  postgres_local:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "inbooks"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"