name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Phase'
        required: true
        type: choice
        options:
          - alpha
          - production
      version_name:
        description: 'Version Name'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Create GCP JSON key files
      run: |
        echo "${{ secrets.gcp_api_json_key_production }}" > gcp_key_production.json
        echo "${{ secrets.gcp_api_json_key_alpha }}" > gcp_key_alpha.json

    - name: Create signing store files
      run: |
        echo "${{ secrets.signing_store_file_base64_production }}" | base64 -d > signing_store_production.keystore
        echo "${{ secrets.signing_store_file_base64_alpha }}" | base64 -d > signing_store_alpha.keystore

    - run: bundle install
      working-directory: client/composeApp

    - run: bundle exec fastlane android deploy_to_${{ github.event.inputs.environment }} version_name:${{ github.event.inputs.version_name }}
      working-directory: client/composeApp
      env:
        gcp_api_json_key_file_path_production: gcp_key_production.json
        signing_store_file_path_production: signing_store_production.keystore
        signing_store_password_production: ${{ secrets.signing_store_password_production }}
        signing_key_alias_production: ${{ secrets.signing_key_alias_production }}
        signing_key_password_production: ${{ secrets.signing_key_password_production }}
        gcp_api_json_key_alpha: gcp_key_alpha.json
        signing_store_file_path_alpha: signing_store_alpha.keystore
        signing_store_password_alpha: ${{ secrets.signing_store_password_alpha }}
        signing_key_alias_alpha: ${{ secrets.signing_key_alias_alpha }}
        signing_key_password_alpha: ${{ secrets.signing_key_password_alpha }}